#! /bin/bash

# Define locations
root=tttotl
bin=$root/bin
libs=lib/'*':junit/'*'

if [ $# -lt 1 ]
then
  echo "Usage: ./jrun pkg.Class args..."
  echo "  for JUnit: ./jrun org.junit.runner.JUnitCore pkg.TestClass"
else
  sudo java -cp $bin:$libs $*
fi
