#! /bin/bash
#
# delusers prefix
# deletes all users whose home directory starts with the prefix (default team)
#

if [ $# -lt 1 ]
then
  prefix="team"
else
  prefix=$1
fi

for i in `ls /home | grep $prefix`
do
  echo "Deleting user $i"
  sudo deluser --remove-home $i
done

